name: Release to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run deploy script
        env:
          GIT_USER_NAME: "github-actions[bot]"
          GIT_USER_EMAIL: "github-actions[bot]@users.noreply.github.com"
          GH_TOKEN: ${{ secrets.GH_ALPHABETS_PAT }}
        run: |
          chmod +x deploy.sh
          ./deploy.sh
